name: Multi Job CI/CD

on:
  push:

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Step
        run: echo "Running the application..."
             sleep 15

  test:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - name: Test Step
        run: echo "Running tests..."
             sleep 10

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Step
        run: echo "Deploying application..."

